#!/bin/sh

DEBSIGN_KEYID=D5609CBE

ARCHIVETOOL=apt-ftparchive

compress() {
  cat "${1}" | gzip - > "${1}.gz"
  cat "${1}" | bzip2 - > "${1}.bz2"
}

# generate index files
${ARCHIVETOOL} packages . > Packages
compress Packages
${ARCHIVETOOL} sources . > Sources
compress Sources

# generate and sign Release file
rm -f Release Release.gpg
${ARCHIVETOOL} release . > Release
gpg --use-agent --local-user ${DEBSIGN_KEYID} -abs -o Release.gpg Release

# Publish the signing key
gpg --use-agent --armor --export-options export-minimal --export ${DEBSIGN_KEYID} > signing-key.asc
